<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.ddd</groupId>
        <artifactId>ddd</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ddd-infrastructure</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.ddd</groupId>
            <artifactId>ddd-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ddd</groupId>
            <artifactId>ddd-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
    </dependencies>
</project>
